const TYPES = {
  ADD_CLIENT: 'ADD_CLIENT',
  CREATE_CLIENT: 'CREATE_CLIENT',
  DELETE_CLIENT: 'DELETE_CLIENT',
  EDIT_CLIENT: 'EDIT_CLIENT',
  GET_CLIENT: 'GET_CLIENT',
  SET_CLIENTS: 'SET_CLIENTS',
  GET_CLIENTS: 'GET_CLIENTS',
  NEW_CLIENT: 'NEW_CLIENT',
  SET_CLIENTS_SEARCHTEXT: 'SET_CLIENTS_SEARCHTEXT',
  SET_SELECTED_CLIENT_ID: 'SET_SELECTED_CLIENT_ID',
  SELECT_CLIENT: 'SELECT_CLIENT',
};

export default TYPES;
