const TYPES = {
  CREATE_PRODUCT: "CREATE_PRODUCT",
  DELETE_PRODUCT: "DELETE_PRODUCT",
  EDIT_PRODUCT: "EDIT_PRODUCT",
  GET_PRODUCT: "GET_PRODUCT",
  SET_PRODUCTS: "SET_PRODUCTS",
  GET_PRODUCTS: "GET_PRODUCTS",
  NEW_PRODUCT: "NEW_PRODUCT",
  GET_CATEGORIES: "GET_CATEGORIES",
  SET_CATEGORIES: "SET_CATEGORIES",
  SET_BASECATEGORIES: "SET_BASECATEGORIES",
  SET_PRODUCTS_SEARCHTEXT: "SET_PRODUCTS_SEARCHTEXT",
};

export default TYPES;
